### ISSUE TITLE
[Feature] : 셀렉션 수정 페이지 구현

### ISSUE THREAD

**Issue by Wongilk** [Programmers-SpotLight/SpotLight#134]
## ✨ 기능 설명

셀렉션 수정 페이지 구현
![image](https://github.com/user-attachments/assets/1c530be2-d0ae-4f60-b9c9-b2c0aedffd99)

## ✅ 할일

- [ ] 기존의 셀렉션 제목, 설명, 카테고리, 썸네일, 스팟, 해시태그, 공개/비공개여부 조회해서 기본값으로 보여줌
- [ ] 사용자의 변경 사항 저장

## ETC
- 생성 페이지 그대로 사용하면 될 것 같아요
-

**Comment by 7jw92nVd1kLaq1** [comment]
👍 👍
