### ISSUE TITLE
[BUG] 셀렉션 생성단계 - 해시태그 추천받기시 에러 

### ISSUE THREAD

**Issue by Eomjihee** [Programmers-SpotLight/SpotLight#253]
## ✨ 버그 설명

해시태그 추천받기 버튼 클릭시 에러

## ✅  예상 해결 방안 

- [ ] 작업 1
- [ ] 작업 2
- [ ] 작업 3

## 📷 스크린 샷
![image](https://github.com/user-attachments/assets/7a6aa009-cb13-4686-9473-92b1c95cb59e)
![image](https://github.com/user-attachments/assets/5c4f7311-7521-486e-8414-18264c31b098)

**Comment by 7jw92nVd1kLaq1** [comment]
에러 발생시 디자인 부탁드립니다
