### ISSUE TITLE
[Refactor] : 파일 업로드 크기 늘리기

### ISSUE THREAD

**Issue by jh0222** [Programmers-SpotLight/SpotLight#254]
## ✨ 기능 설명

구현할 기능 설명
- 파일 업로드 크기 늘리기
- 서버의 구성 파일(예: Nginx, Apache, 혹은 서버 애플리케이션 프레임워크 설정)을 점검하여 현재 허용된 최대 요청 크기를 확인

## ✅ 할일

- [ ] 파일 업로드 크기 늘리기

**Comment by Eomjihee** [comment]
우선 20mb로 수정했는데 에러 났을때 유저 시나리오 알려주시면 테스트해보겠습니다
