### ISSUE TITLE
[BUG] !!! 가장 큰 이슈 !!!

### ISSUE THREAD

**Issue by Eomjihee** [Programmers-SpotLight/SpotLight#257]
## ✨ 버그 설명

Spotlight 어플리케이션 멋대로 내려가는 문제

---
## 추측 가능한 원인
이미지 최적화 문제로 발생하는 이슈가 많은듯함

## ✅  예상 해결 방안 

- [ ] 작업 1
- [ ] 작업 2
- [ ] 작업 3

**Comment by 7jw92nVd1kLaq1** [comment]
현재 서버에서 혹시 AI 서버가 메모리를 얼마나 잡아 먹는지 한번 체크 했는데 약 20%에서 30%를 차지하는 것으로 보입니다. 그래서 그렇게 크게 문제라고 생각하진 않는데, 아마 저희가 이번 회의에서 말한 것과 같이 아마 이미지 최적화를 진행하는데서 메모리 누출에 의해 메모리 사용량이 급격히 증가하는 문제가 왠지 원인이라고 생각이 드네요.

https://github.com/vercel/next.js/issues/44685

여기에서도 약간 비슷한 문제를 겪은 분들이 계시는데, 다들 Next.js에서 제공하는 Image 컴포넌트를 사용하다가 발생하는 문제라고 하는 것 같습니다. 그래서 어떤 분들은 Image 컴포넌트에서 기존 HTML의 img 컴포넌트로 전환하여 문제를 해결했다고 하시는 분들도 계십니다!

다음과 같은 방법들이 문제를 해결할 것이라고 장담할 수는 없지만 왠지 문제 해결에 도움이 되지 않을까 생각합니다.

1. 'sharp' NPM 패키지 설치
  - 빌드에서 발생하는 메시지인데 Next.js에서는 sharp를 사용하여 이미지 최적화를 진행하는 것을 적극적으로 권장합니다. 어떤 분은 이 것을 설치하고 1GB 정도를 사용하던 서버가 약 300MB 정도로 램 사용량이 줄었다고 하시는 분도 봤습니다. 혹시 이 패키지를 설치 방법으로 해결되는지 한 번 보는 것도 좋다고 생각합니다.

2. Image에서 img로 전환
  - 만약에 위에 방법이 현재 문제를 해결하는데 도움이 안될 경우, 파일의 모든 Image를 img로 변환하는 방법 밖에는 없는 것 같습니다. 바꾼 후에 프로젝트의 최상단에 next.config.mjs 파일에서 다음을 추가하면 된다고 합니다.
` images: {
unoptimized: true,
},
}
`
3. Docker로 서버 배포
  - 이전 프로젝트에서는 도커를 사용하여 배포를 진행했는데, 그 당시에는 이러한 문제를 겪지는 않았습니다. 그리고 위에 스레드에서도 어떤 분은 Linux Alpine을 사용한 도커 이미지를 사용할 경우 문제가 발생하지 않는다고 남겨주셨습니다. 혹시 모든 해결책이 도움이 되지 않는다면 최후의 수단으로 이 방법을 시도하는 것을 권장합니다.

혹시 다른 해결책들을 발견하신 분들도 여기에 남겨주시면 감사드리겠습니다!

**Comment by Eomjihee** [comment]
img 사용하게 되면 해당부분은 eslint 부분해제하고 사용해야할 것 같네요 안그럼 빌드가 안돼서..!! 1번은 가장 빠르게 대처할 수 있는 방법이라 어제 적용한 방법인데도 동일한 이슈 발생하고있습니다.

**Comment by 7jw92nVd1kLaq1** [comment]
1번이 되지 않는다면, 조금 번거롭지만 모든 Image 컴포넌트를 img 태그로 변경하는 방법이 최우선이네요 ㅠㅠ 따로 브랜치를 만들어서 모든 Image를 img로 변경하고 한번 해보는 것은 어떤가요?
