### ISSUE TITLE
[BUG] : gpt 해시 태그 추천  x

### ISSUE THREAD

**Issue by Wongilk** [Programmers-SpotLight/SpotLight#259]
## ✨ 버그 설명

셀렉션 생성 시 해시 태그 추천 안됩니다
무한 로딩

## ✅  예상 해결 방안 

- [ ] 작업 1
- [ ] 작업 2
- [ ] 작업 3

## 📷 스크린 샷
![image](https://github.com/user-attachments/assets/38e3cd79-842f-4dba-a802-5d96a551bedd)

**Comment by 7jw92nVd1kLaq1** [comment]
서버의 ENV 파일에 OpenAI API 키가 없습니다
