### ISSUE TITLE
[BUG] : 백엔드 몇 가지 엔드포인트에서 보안 취약점 발견

### ISSUE THREAD

**Issue by 7jw92nVd1kLaq1** [Programmers-SpotLight/SpotLight#272]
## ✨ 버그 설명

API 엔드포인트에서 발견한 보안 문제
- ### /api/users/signup
  - 해당 엔드포인트를 사용하여 무작위로 DB에 사용자를 추가 가능.
  - 해결책?
    - 해결책 마련 필요

- ### /api/selections/spots/[spotsId]/review/[reviewId]/likes
- ### /selections/[selectionId]/reviews/[reviewId]/likes
  - 해당 유저의 ID를 아는 가정하에 유저를 사칭하여 리뷰의 좋아요 생성/삭제 가능
  - 해결책?
    - 유저의 세션을 POST 데이터로 받아오지 않고 해당 유저의 ID를 백엔드에서 토큰을 통하여 추출해서 사용

- ### /selections/[selectionId]/bookmarks 
  - 이것 역시 userId를 POST 데이터로 받아오는 형식으로 북마크를 등록/삭제 기능을 사용 중
  - 문제점?
    - userId와 selectionId를 아는 누구나 userId에 해당하는 유저를 사칭하여 북마크 생성/삭제 가능
  - 해결책?
    - 유저의 세션을 POST 데이터로 받아오지 않고 해당 유저의 ID를 백엔드에서 토큰을 통하여 추출해서 사용 

## ✅  예상 해결 방안 

- [ ] 작업 1
- [ ] 작업 2
- [ ] 작업 3

## 📷 스크린 샷
<img width="877" alt="Screenshot 2024-08-26 at 23 22 10" src="https://github.com/user-attachments/assets/89cfb807-5179-46aa-8b2a-08c42386f7a4">

**Comment by Wongilk** [comment]
좋아요랑 북마크는 백엔드 세션에서 userId값 받아오는 걸로 수정했습니다.
지희님 해결하시면 이슈 닫아주세요!

**Comment by Eomjihee** [comment]
reCAPTCHA 적용하는게 가장 좋은 방법일 것 같아서 오늘 저녁 전에 적용해두겠습니다

**Comment by Eomjihee** [comment]
임의 클로즈
